Milestone 1: Linters setup
DuaneDave/Hello-Microverse pull request #1
Opened 2022-06-28 17:01 UTC by DuaneDave

## Linters Set-up

  In this milestone we happily:

    - added an HTML file 
    - added a stylesheet (CSS 3)
    - added a test file

2022-06-28 17:55 UTC, OmarRamoun requested changes
# 🟡 Almost There! 🏃

## Hi @DuaneDave 👋

## Welcome to Microverse! 🌎

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃

## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights 🌟

- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 17:55 UTC, OmarRamoun commented on .github/linters.yml
> +env:
- [ ] [REQUIRED] Please, make sure to put the `linters.yml` file inside of `.github/workflows`. Yours is under `.github` directly.

2022-06-28 19:16 UTC, DuaneDave commented
Thanks!

I’m having issues reaching you on slack

On Tue, 28 Jun 2022 at 6:55 PM, Ramoun ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> 🟡 Almost There! 🏃 Hi @DuaneDave <https://github.com/DuaneDave> 👋 Welcome
> to Microverse! 🌎
>
> Good job so far! 👏. Your Code is Awesome! 💪
>
> There are some *few* issues 🐛 that you still need to work 🔧 on though
> to go to the next project ⏭️ but you are almost there! 🏃
> Don't Worry 🙏
>
> It's ok to have bugs in your code 🐛. Especially if that's is your first
> project 1️⃣. Please, see this code review as a *chance* for you to *learn*
> practical coding skills and learn *new tips* that can improve your code
> quality 💯 and help you *get a better job* 💼.
>
> *I am going to guide you on how to fix them down below. 🤓*
> Highlights 🌟
>
>    - ✔️ No linter Errors
>    - ✔️ Descriptive README
>    - ✔️ Descriptive PR title and description
>    - The code is top-notch! 💯 and has a huge potential.
>
> Required Changes ♻️
>
> *Check the comments under the review.*
>
> Cheers and Happy coding!👏👏👏
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> *Note:* Please, don't Merge This Pull Request yet. Only Merge when it is
> Approved ✅.
>
> Thank you for your time 🙏 and call me if you need help or clarification
> ☎️
>
>    - This is My *GitHub*: [image: @omarramoun]
>    <https://github.com/omarramoun>
>    - This is My *Twitter*: [image: @omarramoun]
>    <https://twitter.com/omarramoun>
>    - This is My *Slack*: [image: Ramoun] <https://slack.com>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In .github/linters.yml
> <https://github.com/DuaneDave/Hello-Microverse/pull/1#discussion_r908786612>
> :
>
> > +name: Linters
>
> +
>
> +on: pull_request
>
> +
>
> +env:
>
>
>
>    - [REQUIRED] Please, make sure to put the linters.yml file inside of
>    .github/workflows. Yours is under .github directly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DuaneDave/Hello-Microverse/pull/1#pullrequestreview-1022178693>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUH66MZ6IZQC3HKDASCH3UTVRM4B3ANCNFSM52C4ARFA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-29 10:52 UTC, ishimwezachee approved these changes
Hi @DuaneDave , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy-downsized-medium.gif"/>

## Highlights
✔️ No linter Errors
✔️ Descriptive README
✔️ Descriptive PR title and description
The code is top-notch! 💯 and has a huge potential.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 17:05 UTC, merged